version: '3.1'
services:
  #WEBSITE
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html/
    depends_on:
      - db
  #DATABASE
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8091:80'
    volumes:
      - /sessions

volumes:
  database: